### ISSUE TITLE
getRawValue retuns 0, not raw analogread value

### ISSUE THREAD

**Issue by mjs513** [dxinteractive/ResponsiveAnalogRead#19]
In testing I noticed the issue.  the problem is you declared a local variable int rawValue in function ResponsiveAnalogRead::update.  I made a simple change to make update:
```
void ResponsiveAnalogRead::update(int rawValueRead)
{
  rawValue = rawValueRead;
  prevResponsiveValue = responsiveValue;
  responsiveValue = getResponsiveValue(rawValue);
  responsiveValueHasChanged = responsiveValue != prevResponsiveValue;
}
```
Did it this way to avoid issues with global variable and local variable with same name.

**Comment by dxinteractive** [comment]
Oh right, cool. Appears that this isn't a problem if you're using `update()`, but is if you're using `update(rawValue)` directly. #20 looks good, thanks for catching and fixing this!
