### ISSUE TITLE
Smoothing variable

### ISSUE THREAD

**Issue by Frickelpiet** [dxinteractive/ResponsiveAnalogRead#2]
Great Library! Thank you for the time you spent on programming it.

I have one question. I do not want to smooth a value from analog input, but a variable from a light sensor that is connected via I2C. Is this possible with your library? 

Best

Peter

**Comment by lewsut** [comment]
Hello,

As with Frickelpiet I wish to use I2C and can't work out how to pass your lib the info. 

Great work though! excellent visuals ! 

lewsut.

**Comment by cyberponk** [comment]
I agree, it would be great to be able to use this with any input, not only analogRead!

**Comment by lewsut** [comment]
I think you can feed it via analog.update(your input data here) then grab it via analog.getValue() but you sill need to set it up with ResponsiveAnalogRead analog(x, bool).... I think!?

**Comment by paulnd** [comment]
> I agree, it would be great to be able to use this with any input, not only analogRead!

I'll be grateful for this too please

**Comment by dxinteractive** [comment]
Hi all, looks like I'm not receiving notifications for this repo so sorry about the late reply. To do this you can pass a raw reading as an argument to `update`. So then in your project you can read your input by whatever means you like, and pass it's output into `update`. Then `getValue` will return your smoothed value.

When using update like that, the `pin` argument is not used, and no `analogRead` takes place. You may still need to pass a value into the `ResponsiveAnalogRead` constructor though (it doesn't matter what value as it won't be used). Hope this helps.
