### ISSUE TITLE
keeping it from updating all the time.

### ISSUE THREAD

**Issue by Steamedmuffin** [dxinteractive/ResponsiveAnalogRead#6]
when i am useing the libary it outputs data all the time, but i only want it to output when i have changed the value of the potentiometer

if it is even possible, how would this be done?

**Comment by Frickelpiet** [comment]
You could compare the current value with the old value.

**Comment by Steamedmuffin** [comment]
how would this be done?

**Comment by Steamedmuffin** [comment]
i tried something like 
`  if (val != lastVal)`
but it didnt work

**Comment by Steamedmuffin** [comment]
nevermind i fixed it

**Comment by ilikecheese** [comment]
Fixed it how? Please be helpful to the rest of us!

**Comment by Steamedmuffin** [comment]
im just so bad at coding, that i put a semicolon behind the before mentioned if statement, and it canceled itself.... smh.

love the library BTW.

**Comment by ilikecheese** [comment]
Happens to me all the time! Thanks for sharing the fix, it is so much more helpful!
